I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
NameError: name 'name' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\main.py", line 652, in main
    run(restart)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\main.py", line 148, in run
    renpy.execution.run_context(True)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\execution.py", line 958, in run_context
    context.run()
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
  File "lib/python3.9/future/utils/__init__.py", line 444, in raise_
  File "game/script.rpy", line 29, in script
    n"You've created a new Ren'Py game."
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 2579, in execute
    Say.execute(self)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\ast.py", line 621, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\exports\sayexports.py", line 132, in say
    who(what, *args, **kwargs)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1438, in __call__
    who = self.prefix_suffix("who", self.who_prefix, who, self.who_suffix)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1354, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\character.py", line 1334, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 373, in substitute
    s = interpolate(s, variables) # type: ignore
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 86, in interpolate
    raise e
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\substitutions.py", line 78, in interpolate
    value = renpy.python.py_eval(code, {}, scope)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Daniel\Desktop\renpy\renpy-8.3.4-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "<none>", line 1, in <module>
NameError: name 'name' is not defined

Windows-10-10.0.26100 AMD64
Ren'Py 8.3.4.24120703
I Got Hit by A Truck and Reincarnated Into a World Full of Brainrot Memes 1.0
Thu Jan 16 01:00:26 2025
